ANC_test_task/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("urlshortener.urls", namespace="urlshortener")),
]

urlshortener/urls.py
from django.urls import path

from urlshortener.views import LinkCreateViewAPI, LinkCreateView, LinkStatsView, LinkRedirectView, LinkDeleteView, \
    LinkDeleteConfirmView, LinkCreateViewUsingAPI

urlpatterns = [
    path("api/shortner/", LinkCreateViewAPI.as_view(), name="create_short_url_api"),
    path('create-link/', LinkCreateViewUsingAPI.as_view(), name='create_link_using_api'),

    path('shortner/', LinkCreateView.as_view(), name='shortner'),
    path('shortner/<str:symbol>/stats/', LinkStatsView.as_view(), name='link_detail'),
    path('shortner/<str:symbol>/confirm/', LinkDeleteConfirmView.as_view(), name='link_confirm'),
    path('shortner/<str:symbol>/delete/', LinkDeleteView.as_view(), name='link_delete'),
    path('redirect/<str:symbol>/', LinkRedirectView.as_view(), name='redirect'),
]

app_name = "urlshortener"

urlshortener/models.py
import random
import string

from django.db import models

from ANC_test_task.settings import SHORT_HOST


def generate_short_url():
    """
    Function to generate random symbol of 6 characters
    :return: example: "6NpxdR"
    """

    while True:
        short_url = ''.join(random.choice(string.ascii_letters + string.digits + "-") for _ in range(6))
        if not Link.objects.filter(short_url=short_url).exists():
            return SHORT_HOST + short_url


class Link(models.Model):
    long_url = models.URLField()
    short_url = models.CharField(max_length=255, unique=True, default=generate_short_url)
    creator = models.ForeignKey('auth.User', on_delete=models.CASCADE, null=True, blank=True)
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_deleted = models.BooleanField(default=False)

    def get_symbol(self):
        return self.short_url.split("/")[-1]

    def __str__(self):
        return self.short_url


class Click(models.Model):
    link = models.OneToOneField(Link, on_delete=models.CASCADE, related_name="clicks")
    last_clicked_date = models.DateTimeField(auto_now=True)
    clicks_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.link.short_url}: {self.clicks_count}"

urlshortener/forms.py
from django import forms
from .models import Link


class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ('long_url',)

        widget = forms.URLInput(
            attrs={'placeholder': 'https://anc.ua/ru/item/renni-z-apelsinovim-smakom-tabletki-zhuvalni-24-27890',
                   'required': 'true'},
        )

urlshortener/views.py
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.http import JsonResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from rest_framework.response import Response
from rest_framework.views import APIView

from ANC_test_task.settings import SHORT_HOST
from .forms import LinkForm
from .models import Link, Click

from .serializers import LinkSerializer


class LinkCreateViewAPI(APIView):
    """
    API View to create short URL.
    request example: {"long_url": "https://example.com/en/stable/userguide/periodic-tasks1.html"}
    response example:
    {
        "long_url": "https://example.com/en/stable/userguide/periodic-tasks1.html",
        "short_url": "http://127.0.0.1:8000/redirect/gUz2-i"
    }
    """

    def post(self, request):
        long_url = request.data.get('long_url', '')
        existing_link = Link.objects.filter(long_url=long_url).first()
        if existing_link:
            return JsonResponse({"info": f"This URL has already short link - {existing_link.short_url}"}, status=400)
        serializer = LinkSerializer(data=request.data)
        if serializer.is_valid():
            if request.user.is_authenticated:
                serializer.save(creator=request.user)
            else:
                ip_address = request.META.get('REMOTE_ADDR')
                serializer.save(ip_address=ip_address)
            return Response(serializer.data, status=201)
        return Response(serializer.errors, status=400)


class LinkCreateViewUsingAPI(generic.View):
    """
    View to create a short URL using API.
    """
    template_name = 'create_using_api.html'

    def get(self, request):
        return render(request, self.template_name)


class LinkCreateView(generic.CreateView):
    """
    Django view to create short URL in browser
    """

    template_name = "create_short_url.html"
    form_class = LinkForm

    def form_valid(self, form):
        existing_link = Link.objects.filter(long_url=form.cleaned_data["long_url"]).first()
        if existing_link:
            return render(self.request, template_name='link_consists.html', context={"link": existing_link})

        if self.request.user.is_authenticated:
            form.instance.creator = self.request.user
        else:
            form.instance.ip_address = self.request.META.get('REMOTE_ADDR')
        try:
            return super().form_valid(form)
        except ValidationError as e:
            messages.error(self.request, e.message)
            return self.form_invalid(form)

    def get_success_url(self):
        Click.objects.create(link=self.object)
        return reverse_lazy("urlshortener:link_detail", kwargs={'symbol': self.object.get_symbol()})


class LinkStatsView(generic.DetailView):
    """
    Django view to get detail info about short link (clicks, last click).
    Only creator can get this information
    """

    model = Link
    template_name = 'link_detail.html'

    def get_object(self, queryset=None):
        symbol = self.kwargs.get('symbol')
        short_url = SHORT_HOST + symbol
        return get_object_or_404(Link, short_url=short_url, is_deleted=False)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.creator == request.user or self.object.ip_address == request.META.get('REMOTE_ADDR'):
            context = self.get_context_data(object=self.object)
            return self.render_to_response(context)
        raise Http404("You are not authorized to view this page")


class LinkDeleteConfirmView(generic.TemplateView):
    """
    Confirmation page
    """

    template_name = 'link_confirm_delete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        symbol = self.kwargs.get('symbol')
        short_url = SHORT_HOST + symbol
        context['object'] = get_object_or_404(Link, short_url=short_url)
        return context


class LinkDeleteView(generic.View):
    """
    Django view to "delete" link from DB.
    It's only change status of is_deleted to True
    """

    success_url = reverse_lazy('urlshortener:shortner')

    def post(self, request, symbol):

        short_url = SHORT_HOST + symbol
        obj = get_object_or_404(Link, short_url=short_url)
        if obj.creator == request.user or obj.ip_address == request.META.get('REMOTE_ADDR'):
            obj.is_deleted = True
            obj.save()
            return HttpResponseRedirect(self.success_url)
        raise Http404("You are not authorized to delete this link")


class LinkRedirectView(generic.RedirectView):
    """
    Django view to redirect from short link to original link
    """

    def get_redirect_url(self, *args, **kwargs):
        short_url = SHORT_HOST + kwargs.get('symbol')
        link = get_object_or_404(Link, short_url=short_url)
        try:
            click = Click.objects.get(link=link)
        except Click.DoesNotExist:
            click = Click.objects.create(link=link)
        click.clicks_count += 1
        click.save()
        return link.long_url

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>ANC Test Task</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
</head>

<body>


{% block content %}{% endblock %}


</body>

</html>

templates/create_short_url.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container">
    <h1>Create Link</h1>
    <form method="post" action="{% url 'urlshortener:shortner' %}" class="form-narrow">
      {% csrf_token %}
      {{ form|crispy }}
      <button class="btn btn-success" type="submit">Short it!</button>
    </form>
  </div>
{% endblock %}

<style>
  .form-narrow {
    max-width: 400px;
    margin: 0 auto;
  }
</style>

templates/create_using_api.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h1>Create Short URL</h1>
    <form id="create-url-form">
      <div class="form-group">
        <label for="long-url-input">Long URL:</label>
        <input type="text" class="form-control" id="long-url-input" name="long_url">
      </div>
      <button type="submit" class="btn btn-primary">Create Short URL</button>
    </form>
    <div id="short-url-container"></div>
  </div>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    $(document).ready(function() {
      $('#create-url-form').submit(function(event) {
        event.preventDefault();
        var longUrl = $('#long-url-input').val();
        $.ajax({
          url: "{% url 'urlshortener:create_short_url_api' %}",
          method: "POST",
          data: { long_url: longUrl },
          success: function(response) {
            var shortUrl = response.short_url;
            $('#short-url-container').html('<p>Short URL: <a href="' + shortUrl + '">' + shortUrl + '</a></p>');
          },
          error: function(xhr, status, error) {
            var message = xhr.responseJSON.info;
            $('#short-url-container').html('<p class="text-danger">' + message + '</p>');
          }
        });
      });
    });
  </script>
{% endblock %}

templates/link_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-center align-items-center" style="height: 40vh; margin-top: 1px;">
    <form method="post" action="{% url 'urlshortener:link_delete' symbol=object.get_symbol %}" class="text-center">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <p><b>There is no undo for this process!</b></p>
        <button type="submit" class="btn btn-danger">
            Confirm
        </button>
    </form>
</div>
{% endblock content %}

templates/link_consists.html
{% extends 'base.html' %}

{% block content %}
    <div class="" style="height: 40vh; margin-top: 40px;">
        <p class="text-center">This URL has already short link - "<a
                href="{{ link.short_url }}">{{ link.short_url }}</a>"</p>
        <div class="d-flex flex-column align-items-center">
            <form action="{% url 'urlshortener:shortner' %}">
                <input class="btn btn-success" type="submit" value="Create new short URL!"/>
            </form>
        </div>
    </div>
{% endblock content %}

templates/link_detail.html
{% extends 'base.html' %}

{% block content %}
    <table class="table">
        <tr>
            <th>Long URL:</th>
            <th>Short URL:</th>
            <th>Clicks:</th>
            <th>Last clicked at:</th>
            <th>Delete:</th>
        </tr>

        <tr>
            <td>
                <a href="{{ link.long_url }}">{{ link.long_url }}</a>
            </td>
            <td>
                <a href="{{ link.short_url }}">{{ link.short_url }}</a>
            </td>
            <td>
                {{ object.clicks.clicks_count }}
            </td>
            <td>
                {{ object.clicks.last_clicked_date }}
            </td>
            <td>
                <a class="text-danger" href="{% url 'urlshortener:link_confirm' symbol=link.get_symbol %}">Delete</a>
            </td>
        </tr>
    </table>

    <form action="{% url 'urlshortener:shortner' %}">
        <button type="submit" class="btn btn-success">
            <i class="fas fa-plus-circle"></i> Create new short URL
        </button>
    </form>

{% endblock %}